// 键区：0～67
#define HFDKB_IND_KEY_FIRST 0
#define HFDKB_IND_KEY_COUNT 68

// Logo：68～74
#define HFDKB_IND_LOGO_FIRST 68
#define HFDKB_IND_LOGO_COUNT 7

#define HFDKB_IND_LOW_BAT_LED 74

// 以下时间单位全部是毫秒。
// on/off 表示每次亮、灭的时间；duration 表示总持续时间。
#define HFDKB_IND_BT_PAIR_ON_MS 200
#define HFDKB_IND_BT_PAIR_OFF_MS 200
#define HFDKB_IND_BT_PAIR_DURATION_MS 60000

#define HFDKB_IND_BT_RECONNECT_ON_MS 500
#define HFDKB_IND_BT_RECONNECT_OFF_MS 500
#define HFDKB_IND_BT_RECONNECT_DURATION_MS 10000

#define HFDKB_IND_2G4_PAIR_ON_MS 200
#define HFDKB_IND_2G4_PAIR_OFF_MS 200
#define HFDKB_IND_2G4_PAIR_DURATION_MS 60000

#define HFDKB_IND_2G4_RECONNECT_ON_MS 500
#define HFDKB_IND_2G4_RECONNECT_OFF_MS 500
#define HFDKB_IND_2G4_RECONNECT_DURATION_MS 10000

#define HFDKB_IND_CONNECTED_DURATION_MS 2000

#define HFDKB_IND_RESET_ON_MS 200
#define HFDKB_IND_RESET_OFF_MS 200
#define HFDKB_IND_RESET_DURATION_MS 1200

#define HFDKB_IND_LOW_BAT_ON_MS 500
#define HFDKB_IND_LOW_BAT_OFF_MS 1500
